helloflask/models.py
import sys

from sqlalchemy import Column, ForeignKey, Integer, String, Table
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, backref
from sqlalchemy import create_engine


Base = declarative_base()

class User(Base):

    __tablename__ = 'user'

    id = Column(Integer,primary_key=True)
    username = Column(String(32), nullable=False)
    password = Column(String(256), nullable=False)

engine = create_engine('sqlite:///test.db')

Base.metadata.create_all(engine)

helloflask/__init__.py
from flask import Flask

app = Flask(__name__)


UPLOAD_FOLDER = 'static'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

app.secret_key = 'super_secret_key'

from . import views
from .auth import auth_blueprint

app.register_blueprint(auth_blueprint)

helloflask/auth.py
from flask import Blueprint

auth_blueprint = Blueprint('auth', __name__, template_folder='templates')

@auth_blueprint.route('/auth/')
def auth():
    return "authentication success"

helloflask/views.py
from helloflask import app

from flask import flash, request, render_template, redirect, url_for

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from models import *

@app.route('/')
def index():
    return render_template("index.html")

@app.route('/pic/')
def pic():
    return render_template("picture.html")

@app.route('/form/', methods=["GET", "POST"])
def form():
    if request.method == "GET":
        return render_template("form.html")

    return "Form submited"

helloflask/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% endblock %}
</head>
<body>
    <header>
        <ul>
            <li><a href="{{ url_for('index') }}">Index</a></li>
            <li><a href="{{ url_for('form') }}">Form</a></li>
            <li><a href="{{ url_for('pic') }}">Picture</a></li>
            <li><a href="{{ url_for('auth.auth') }}">Authentication</a></li>
        </ul>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer></footer>
</body>
</html>

helloflask/templates/form.html
{% extends "base.html" %}
{% block title %}Form{% endblock %}
{% block content %}
<div>
    <form action="{{ url_for('form') }}" method="POST">
        <input type="text" name="input" placeholder="input">
        <input type="submit" value="SUBMIT">
    </form>
</div>
{% endblock %}

helloflask/templates/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}
{% block content %}
<div>
    Hello, World
</div>
{% endblock %}

helloflask/templates/picture.html
{% extends "base.html" %}
{% block title %}Picture{% endblock %}
{% block content %}
<div>
    <img src="{{ url_for('static', filename='images/test.png') }}" alt="picture">
</div>
{% endblock %}